[project]
name = "pricing-term-structure"
version = "1.0.3"
description = "Pricing polish term structure with QuantLib"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiolimiter>=1.2.1",
    "beautifulsoup4>=4.13.5",
    "html5lib>=1.1",
    "httpx>=0.28.1",
    "httpx-limiter>=0.4.0",
    "jinja2>=3.1.6",
    "lxml>=6.0.1",
    "matplotlib>=3.10.6",
    "nbconvert>=7.16.6",
    "pyacm>=1.0",
    "pyarrow>=21.0.0",
    "quantlib>=1.39",
    "scipy>=1.16.2",
    "xlrd>=2.0.2",
]
